# Generated by Django 2.0 on 2019-11-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingInformation',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SessionKey', models.CharField(max_length=30)),
                ('QuestionID', models.IntegerField()),
                ('Answer', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_onboarding',
            },
        ),
    ]
