# Generated by Django 2.0 on 2019-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronboardinginformation',
            name='created',
        ),
        migrations.AlterField(
            model_name='useronboardinginformation',
            name='SessionKey',
            field=models.CharField(max_length=50),
        ),
    ]
