# Generated by Django 2.0 on 2019-11-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_auto_20191124_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useronboardinginformation',
            old_name='SessionKey',
            new_name='Session',
        ),
    ]
