# Generated by Django 2.0 on 2019-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0003_auto_20191124_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronboardinginformation',
            name='Session',
        ),
        migrations.AddField(
            model_name='useronboardinginformation',
            name='Skey',
            field=models.IntegerField(default=0),
        ),
    ]
